### PR TITLE
Changes the background job status to use Jobba

### PR DESCRIPTION
**Pull request by jpslav**
1. Updates Lev to use Ruby 2.2.3 by default

### CODE REVIEW

**Comment by jpslav** [comment]
@Dantemss can you review?

**Comment by Dantemss** [comment]
Seems fine overall, but I think there are a couple bugs somewhere either in Lev or Jobba (see comments on https://github.com/openstax/tutor-server/pull/941)

**Comment by jpslav** [comment]
@Dantemss I released Jobba 1.4.0.  Can you incorporate here / tutor-server?

**Comment by Dantemss** [comment]
OK

**Pull request merged**
